### PR TITLE
docs: add missing closing bracket in readme

### PR DESCRIPTION
**Pull request by Chetax**

### CODE REVIEW

**Comment by gamemaker1** [comment]
Thanks for the PR!

**Comment by rahul101001000** [comment]
Hey Chetan nice start.. do keep submitting PRs for things you notice like these on any repo. And if you do these for the issue list, that means it is important to the repo owner too!

**Comment by Chetax** [comment]
Ok Sir 😃.

Thanks & Regards
Chetan Padhen

**Comment by Chetax** [comment]
Ok Sir 😃.
Thanks

**Pull request merged**
